version: '3.3'

services:
  smirp_server:
    container_name: smirp-server
    build: .
    restart: always
    environment:
      - FLASK_DEBUG=1
    expose:
      - 3001
    ports:
      - 3001:3001
    volumes:
      - .:/app
