/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/jrgreen/smirp/smirp/progs/perl-5.14.2/miniperl ../bin/enc2xs -Q -O -o symbol_t.c -f symbol_t.fnm
 enc2xs VERSION 2.07
*/
extern encode_t AdobeSymbol_encoding;
extern encode_t AdobeZdingbat_encoding;
extern encode_t MacDingbats_encoding;
extern encode_t MacSymbol_encoding;
extern encode_t dingbats_encoding;
extern encode_t symbol_encoding;
