/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/jrgreen/smirp/smirp/progs/perl-5.14.2/miniperl ../bin/enc2xs -Q -o ks_03_t.c -f ks_03_t.fnm
 enc2xs VERSION 2.07
*/
extern encode_t ksc5601_raw_encoding;
