/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/jrgreen/smirp/smirp/progs/perl-5.14.2/miniperl ../bin/enc2xs -Q -o gb_02_t.c -f gb_02_t.fnm
 enc2xs VERSION 2.07
*/
extern encode_t gb12345_raw_encoding;
